USE SOCCER_GUESS;
DROP TABLE IF EXISTS SG_GROUPS;

CREATE TABLE SG_GROUPS (
  'ID'    TINYINT(5) NOT NULL UNIQUE AUTO_INCREMENT ,
  'NAME'  CHAR(1) NOT NULL UNIQUE,
  PRIMARY KEY(ID)
); 

 INSERT INTO SG_GROUPS VALUES
  (NULL,'A'),
  (NULL,'B'),
  (NULL,'C'),
  (NULL,'D'),
  (NULL,'E'),
  (NULL,'F'),
  (NULL,'G'),
  (NULL,'H');