USE SOCCER_GUESS;

DROP TABLE IF EXISTS SG_TOURNAMENTS;

CREATE TABLE SG_TOURNAMENTS (
    'ID' TINYINT NOT NULL UNIQUE AUTO_INCREMENT,
    'NAME' VARCHAR(150) NOT NULL,
    'FLAG' VARCHAR(255) DEFAULT 'tournament_flag.png'
);