-- SET THE DEFAULT SCHEMA
-- USE u989271099_sg;
USE SOCCER_GUESS;

-- DROPPING TABLES
DROP TABLE IF EXISTS SG_GROUP_FORMATIONS;
DROP TABLE IF EXISTS SG_GROUPS;
DROP TABLE IF EXISTS SG_TOURNAMENTS;
DROP TABLE IF EXISTS SG_TEAMS;

-- CREATES A TABLE CONTAINING ALL TOURNAMENTS
CREATE TABLE SG_TOURNAMENTS (
    `ID` TINYINT NOT NULL UNIQUE AUTO_INCREMENT,
    `NAME` VARCHAR(150) NOT NULL,	
    `FLAG` VARCHAR(255) NULL DEFAULT 10,
    `ACTIVE` TINYINT(1) NULL DEFAULT 1,
    PRIMARY KEY(ID)
);

-- CREATES A TABLE CONTAINING ALL TEAMS
CREATE TABLE SG_TEAMS (
  `ID`         INT NOT NULL AUTO_INCREMENT,
  `FULLNAME`   VARCHAR(100) NOT NULL UNIQUE,
  `SHORTNAME`  CHAR(3) NOT NULL,
  `FLAG`       VARCHAR(255) DEFAULT 'team_flag.png',
  `ACTIVE`	   TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY(ID)
);

-- CREATES A TABLE CONTAINING ALL GROUPS OF ALL TOURNAMENTS
-- CREATE TABLE SG_GROUPS (
--     `ID` INT NOT NULL UNIQUE AUTO_INCREMENT,
--     `NAME` VARCHAR(2) NOT NULL,
--     `TOURNAMENT_ID` TINYINT NOT NULL,
--     FOREIGN KEY(TOURNAMENT_ID) REFERENCES SG_TOURNAMENTS(ID) 
-- );
-- 
-- -- CREATES A TABLE CONTAINING ALL GROUPS FORMATIONS
-- CREATE TABLE SG_GROUP_FORMATIONS (
--     `GROUP_ID` INT NOT NULL,
--     `TEAM_ID` INT NOT NULL,
--     PRIMARY KEY(GROUP_ID,TEAM_ID),
--     FOREIGN KEY(TEAM_ID) REFERENCES SG_TEAMS(ID),
--     FOREIGN KEY(GROUP_ID) REFERENCES SG_GROUPS(ID)
-- );
-- 

