DROP DATABASE IF EXISTS SOCCER_GUESS;

CREATE DATABASE SOCCER_GUESS;
USE SOCCER_GUESS;

-- CREATES A TABLE CONTAINING ALL TEAMS
DROP TABLE IF EXISTS SG_TEAMS;

CREATE TABLE SG_TEAMS (
  `ID`           INT NOT NULL AUTO_INCREMENT,
  `FULLNAME`     VARCHAR(100) NOT NULL UNIQUE,
  `SHORTNAME`    CHAR(3) NOT NULL,
  `FLAG`         VARCHAR(255) DEFAULT 'team_flag.png',
  PRIMARY KEY(ID)
);

-- CREATES A TABLE CONTAINING ALL TOURNAMENTS
DROP TABLE IF EXISTS SG_TOURNAMENTS;

CREATE TABLE SG_TOURNAMENTS (
    `ID` TINYINT NOT NULL UNIQUE AUTO_INCREMENT,
    `NAME` VARCHAR(150) NOT NULL,	
    `FLAG` VARCHAR(255) NULL DEFAULT 10,
    `ACTIVE` TINYINT(1) NULL DEFAULT 1,
    PRIMARY KEY(ID)
);

-- CREATES A TABLE CONTAINING ALL GROUPS OF ALL TOURNAMENTS
DROP TABLE IF EXISTS SG_GROUPS;

CREATE TABLE SG_GROUPS (
    `ID` INT NOT NULL UNIQUE AUTO_INCREMENT,
    `NAME` VARCHAR(2) NOT NULL,
    `TOURNAMENT_ID` TINYINT NOT NULL,
    FOREIGN KEY(TOURNAMENT_ID) REFERENCES SG_TOURNAMENTS(ID) 
);

-- CREATES A TABLE CONTAINING ALL GROUPS FORMATIONS
DROP TABLE IF EXISTS SG_GROUP_FORMATIONS;

CREATE TABLE SG_GROUP_FORMATIONS (
    `GROUP_ID` INT NOT NULL,
    `TEAM_ID` INT NOT NULL,
    PRIMARY KEY(GROUP_ID,TEAM_ID),
    FOREIGN KEY(TEAM_ID) REFERENCES SG_TEAMS(ID),
    FOREIGN KEY(GROUP_ID) REFERENCES SG_GROUPS(ID)
);


-- DATA INSERTION PROCESS

-- CREATE A TOURNAMENT
INSERT INTO SG_TOURNAMENTS VALUES
	(NULL, "WORLD CUP 2018",'RUSSIA-2018_flag.png'),
    (NULL, "FIFA SOUTH AMERICA'S QUALIFIERS - RUSSIA 2018",'south_america_qual_2018.png');

-- CREATE A GROUP FOR THIS TOURNAMENT
INSERT INTO SG_GROUPS VALUES
  (NULL,'A',1);
  
-- CREATE A TEAM
INSERT INTO SG_TEAMS VALUES
	(NULL,'BRAZIL','BRA','BRAZIL_flag.png');

-- INSERT IT INTO A GROUP
INSERT INTO SG_GROUP_FORMATIONS VALUES
	(1,1);

